---
- hosts: 127.0.0.1
  connection: local
  become: true

  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]
   
    - name: install zsh + theme
      tags: always
      pacman:
        name: zsh,grml-zsh-config
    - name: install nvidia xorg gnome
      pacman:
        name: nvidia,nvidia-utils,lib32-nvidia-utils,xorg-server,gnome,gdm
    - name: enable gdm
      systemd:
        name: gdm
        state: enabled

    - name: add apeku user
      tags: always
      user:
        name: apeku
        shell: /bin/zsh
        append: yes
  tasks: 
  - name: install flatpak, snap
    package:
      name: flatpak,snapd  
  - name: download aur helper for ansible
    git:
      repo: https://github.com/pigmonkey/ansible-aur.git
      dest: /tmp/install
  - name: install aur helper for ansible
    copy:
      src: /tmp/insatall/aur
      dest: /usr/share/ansible
   
  - name: install packages
    package:
      name: htop,openssh,terminator,codeblocks,base-devel,ark,discord,firefox,python-psutil
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: apeku
    dconf:
      key: "/org/gnome/destop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: apeku 
    dconf:
      key: "/org/gnome/destop/background/picture-options" 
      value: "'zoom'"
  - name: add ansible user
    user:
      name: velociraptor
      system: yes
  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Esei10/ansible_auto_config.git
