---
- hosts: 127.0.0.1
  connection: local
  become: true
  
  tasks:
  - name: install packages
    package:
      name: htop,openssh,terminator,spotifyd,spotify-launcher,codeblocks,base-devel,ark,discord,firefox,python-psutil,zsh,grml-zsh-config
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: apeku
    dconf:
      key: "/org/gnome/destop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: apeku 
    dconf:
      key: "/org/gnome/destop/background/picture-options" 
      value: "'zoom'"
  - name: add ansible user
    user:
      name: velociraptor
      system: yes
  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440
  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: velociraptor
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/Esei10/ansible_auto_config.git
